spring:
  shardingsphere:
    datasource:
      names: d0,d1
      d0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/demo_ds_0?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
        password:
      d1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/demo_ds_1?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
        password:
    sharding:
      tables:
        t_order:
          actualDataNodes: d$->{0..1}.t_order$->{0..1}
          databaseStrategy:
            complex:
              shardingColumns: id, user_id
              algorithmClassName: komachi.sion.algorithm.BaseComplexKeysShardingAlgorithm
          tableStrategy:
            complex:
              shardingColumns: id, user_id
              algorithmClassName: komachi.sion.algorithm.BaseComplexKeysShardingAlgorithm
          keyGenerator:
            type: SNOWFLAKE
            column: order_id
    props:
      sql:
        show: true