spring:
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: dsa
      dsa:
        pool-name: dsa
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_0?useUnicode=true
        username: root
        password: ''
    sharding:
      default-data-source-name: dsa