spring:
  datasource:
      username: root
# MySQL
#      password: root
#      url: jdbc:mysql://localhost:3307/issue2687
#      driver-class-name: com.mysql.jdbc.Driver

# PostgreSQL
      password: 1
      url: jdbc:postgresql://localhost:5432/demo_ds_0
      driver-class-name: org.postgresql.Driver